name: check-label-then-build-and-deploy
on:
  issues:
    types: [labeled]

jobs:
  checkLabel:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'tools') || contains(github.event.issue.labels.*.name, 'fundamentals')
    steps:
      - name: checkout the book
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0


      - name: setup python
        uses: actions/setup-python@v4

      - run: python rain.py

      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/seprate'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      - name: Commit files
        run: |
          git config --local user.email "m.mohamadshabane@gmail.com"
          git config --local user.name "shabane"
          git add --all
          git commit -m "Auto commiting changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: Thanks for your contribution, we added this chapter to the book :)